export const motivationQuotes = [
  "“A goal without a plan is just a wish.” — Antoine de Saint-Exupéry",
  "“Setting goals is the first step in turning the invisible into the visible.” — Tony Robbins",
  "“What you get by achieving your goals is not as important as what you become by achieving your goals.” — Zig Ziglar",
  "“By failing to prepare, you are preparing to fail.” — Benjamin Franklin",
  "“Discipline is the bridge between goals and accomplishment.” — Jim Rohn",
  "“If you aim at nothing, you will hit it every time.” — Zig Ziglar",
  "“Success is the progressive realization of a worthy goal.” — Earl Nightingale",
  "“A good plan today is better than a perfect plan tomorrow.” — George S. Patton",
  "“Goals are dreams with deadlines.” — Diana Scharf",
  "“You are never too old to set another goal or to dream a new dream.” — C.S. Lewis",
  "“What seems to us as bitter trials are often blessings in disguise.” — Oscar Wilde",
  "“The secret of getting ahead is getting started.” — Mark Twain",
  "“You miss 100% of the shots you don’t take.” — Wayne Gretzky",
  "“Vision without action is a daydream.” — Japanese proverb",
  "“Action without planning is the cause of failure.” — Unknown",
  "“Success usually comes to those who are too busy to be looking for it.” — Henry David Thoreau",
  "“One way to keep momentum going is to have constantly greater goals.” — Michael Korda",
  "“A year from now you may wish you had started today.” — Karen Lamb",
  "“Begin with the end in mind.” — Stephen R. Covey",
  "“The only limit to our realization of tomorrow will be our doubts of today.” — Franklin D. Roosevelt",
  "“It always seems impossible until it’s done.” — Nelson Mandela",
  "“Without hustle, your talent will only get you so far.” — Gary Vaynerchuk",
  "“Dream big. Start small. Act now.” — Robin Sharma",
  "“A plan is a list of actions arranged in whatever sequence is thought likely to achieve an objective.” — Peter F. Drucker",
  "“Small deeds done are better than great deeds planned.” — Peter Marshall",
  "“Goals transform a random walk into a chase.” — Mihaly Csikszentmihalyi",
  "“The future depends on what you do today.” — Mahatma Gandhi",
  "“What you do today can improve all your tomorrows.” — Ralph Marston",
  "“You don’t have to see the whole staircase, just take the first step.” — Martin Luther King Jr.",
  "“If you want to live a happy life, tie it to a goal.” — Albert Einstein",
  "“Success is the sum of small efforts repeated day in and day out.” — Robert Collier",
  "“Plans are nothing; planning is everything.” — Dwight D. Eisenhower",
  "“The tragedy of life is not that it ends so soon but that we wait so long to begin it.” — W.M. Lewis",
  "“What’s the point of being alive if you don’t at least try to do something remarkable.” — John Green",
  "“Forward ever, backward never.” — Kwame Nkrumah",
  "“You must take action now that will move you toward your goals.” — Les Brown",
  "“Your goals are the road maps that guide you and show you what is possible.” — Les Brown",
  "“Don’t watch the clock; do what it does. Keep going.” — Sam Levenson",
  "“A year from now you will wish you started today.” — Unknown",
  "“The best way to predict the future is to create it.” — Peter Drucker",
  "“Start where you are. Use what you have. Do what you can.” — Arthur Ashe",
  "“Each morning we are born again. What we do today matters most.” — Buddha",
  "“Your life does not get better by chance, it gets better by change.” — Jim Rohn",
  "“Great things never come from comfort zones.” — Unknown",
  "“You don’t have to be great to start, but you have to start to be great.” — Zig Ziglar",
  "“The journey of a thousand miles begins with a single step.” — Lao Tzu",
  "“Dedication sees dreams come true.” — Kobe Bryant",
  "“Goals are the fuel in the furnace of achievement.” — Brian Tracy",
  "“The only thing standing between you and your goal is the story you keep telling yourself.” — Jordan Belfort",
  "“Don’t be pushed by your problems. Be led by your dreams.” — Ralph Waldo Emerson",
  "“Success is dependent on effort.” — Sophocles",
  "“To think is easy. To act is hard.” — Johann Wolfgang von Goethe",
  "“The wise does at once what the fool does at last.” — Baltasar Gracián",
  "“The best way out is always through.” — Robert Frost",
  "“Make your life a masterpiece.” — Brian Tracy",
  "“Champions keep playing until they get it right.” — Billie Jean King",
  "“Do something today that your future self will thank you for.” — Sean Patrick Flanery",
  "“Action expresses priorities.” — Mahatma Gandhi",
  "“The way to get started is to quit talking and begin doing.” — Walt Disney",
  "“If opportunity doesn’t knock, build a door.” — Milton Berle",
  "“Don’t let yesterday take up too much of today.” — Will Rogers",
  "“Everything you’ve ever wanted is on the other side of fear.” — George Addair",
  "“Failure is success in progress.” — Albert Einstein",
  "“It is never too late to be what you might have been.” — George Eliot",
  "“Act or accept.” — Anonymous (military maxim)",
  "“Dreams are extremely important. You can’t do it unless you imagine it.” — George Lucas",
  "“Quality is not an act, it is a habit.” — Aristotle",
  "“It’s not about ideas. It’s about making ideas happen.” — Scott Belsky",
  "“The secret of success is constancy to purpose.” — Benjamin Disraeli",
  "“The best revenge is massive success.” — Frank Sinatra",
  "“There is no substitute for hard work.” — Thomas Edison",
  "“Action cures fear.” — David J. Schwartz",
  "“Never give up, for that is just the place and time that the tide will turn.” — Harriet Beecher Stowe",
  "“Everything begins with an idea.” — Earl Nightingale",
  "“The secret of getting things done is to act!” — Dante Alighieri",
  "“Your big opportunity may be right where you are now.” — Napoleon Hill",
  "“Nothing will work unless you do.” — Maya Angelou",
  "“In all things that you do, consider the end.” — Solon",
  "“To reach a great height, a person must have great depth.” — Unknown",
  "“All achievements begin with a desire.” — Napoleon Hill",
  "“Life shrinks or expands in proportion to one’s courage.” — Anaïs Nin",
  "“Don’t count the days; make the days count.” — Muhammad Ali",
  "“The harder the battle, the sweeter the victory.” — Les Brown",
  "“A champion is defined not by their wins but by how they recover.” — Serena Williams",
  "“You become what you think about.” — Earl Nightingale",
  "“Start where you are and move forward.” — Unknown",
  "“Be willing to be a beginner every single morning.” — Meister Eckhart",
  "“He who is not courageous enough to take risks will accomplish nothing.” — Muhammad Ali",
  "“The starting point of all achievement is desire.” — Napoleon Hill",
  "“The future starts today, not tomorrow.” — Pope John Paul II",
  "“Hard choices, easy life. Easy choices, hard life.” — Jerzy Gregorek",
  "“When you feel like quitting, think about why you started.” — Unknown",
  "“Success is doing ordinary things extraordinarily well.” — Jim Rohn",
  "“You cannot swim for new horizons until you have courage to lose sight of the shore.” — William Faulkner",
  "“One step at a time is enough.” — Mother Teresa",
  "“If you get tired, learn to rest, not quit.” — Banksy",
  "“The secret of change is to focus all your energy on building the new.” — Socrates",
  "“Our greatest glory is not in never falling, but in rising every time we fall.” — Confucius",
  "“Aim for the moon. If you miss, you may hit a star.” — W. Clement Stone",
  "“Hard work beats talent when talent doesn’t work hard.” — Tim Notke",
  "“You can do anything you set your mind to.” — Benjamin Franklin",
  "“The expert in anything was once a beginner.” — Helen Hayes",
  "“Be not afraid of going slowly; be afraid only of standing still.” — Chinese proverb",
  "“Success is not final; failure is not fatal.” — Winston Churchill",
  "“Productivity is never an accident.” — Paul J. Meyer",
  "“A goal is not always meant to be reached; it often serves simply as something to aim at.” — Bruce Lee",
  "“You are what you repeatedly do.” — Will Durant",
  "“Success has a simple formula: do your best and people may like it.” — Sam Ewing",
  "“The future is something which everyone reaches at the rate of 60 minutes an hour.” — C.S. Lewis",
  "“Your passion is waiting for your courage to catch up.” — Isabelle Lafleche",
  "“Work gives you meaning and purpose.” — Stephen Hawking",
  "“Don’t be distracted by criticism.” — Walt Disney",
  "“It’s never crowded along the extra mile.” — Wayne Dyer",
  "“Small progress is still progress.” — Unknown",
  "“The man who moves a mountain begins by carrying away small stones.” — Confucius",
  "“Act as if it were impossible to fail.” — Dorothea Brande",
  "“Motivation is what gets you started. Habit is what keeps you going.” — Jim Ryun",
  "“If you want to achieve greatness stop asking for permission.” — Unknown",
  "“Don’t limit your challenges. Challenge your limits.” — Jerry Dunn",
  "“Life is 10% what happens to you and 90% how you react to it.” — Charles R. Swindoll",
  "“Success isn’t given. It’s earned.” — LeBron James",
  "“Be so good they can’t ignore you.” — Steve Martin",
  "“There is no elevator to success. You have to take the stairs.” — Zig Ziglar",
  "“Work hard in silence; let success make the noise.” — Frank Ocean",
  "“You can’t cross the sea merely by standing and staring at the water.” — Rabindranath Tagore",
  "“To accomplish great things, we must not only act, but also dream.” — Anatole France",
  "“Success occurs when opportunity meets preparation.” — Zig Ziglar",
  "“Fall seven times, stand up eight.” — Japanese proverb",
  "“The journey is the reward.” — Steve Jobs",
  "“Success is born out of faith.” — Helen Keller",
  "“He who fails to plan is planning to fail.” — Winston Churchill",
  "“Don’t wish it were easier; wish you were better.” — Jim Rohn",
  "“All our dreams can come true, if we have the courage to pursue them.” — Walt Disney",
  "“If you’re going through hell, keep going.” — Winston Churchill",
  "“Success consists of going from failure to failure without loss of enthusiasm.” — Winston Churchill",
  "“It’s not whether you get knocked down; it’s whether you get up.” — Vince Lombardi",
  "“Greatness is a lot of small things done well.” — Ray Lewis",
  "“You must do the things you think you cannot do.” — Eleanor Roosevelt",
  "“The door of opportunity is wide open — but you must walk through it.” — Unknown",
  "“Keep your eyes on the stars and your feet on the ground.” — Theodore Roosevelt",
  "“Never bend your head. Hold it high.” — Helen Keller",
  "“What lies behind us and what lies before us are tiny matters compared to what lies within us.” — Ralph Waldo Emerson",
  "“Courage starts with showing up and letting ourselves be seen.” — Brené Brown",
  "“If you change nothing, nothing will change.” — Tony Robbins",
  "“The best dreams happen when you’re awake.” — Cherie Gilderbloom",
  "“Everything you can imagine is real.” — Pablo Picasso",
  "“Action is the antidote to despair.” — Joan Baez",
  "“Doubt kills more dreams than failure ever will.” — Suzy Kassem",
  "“Goals give you a compass.” — Earl Nightingale",
  "“Your life is your message to the world.” — Mahatma Gandhi",
  "“Believe you can and you’re halfway there.” — Theodore Roosevelt",
  "“Do more of what makes you happy.” — Unknown",
  "“You cannot plow a field by turning it over in your mind.” — Gordon B. Hinckley",
  "“We are what we believe we are.” — C.S. Lewis",
  "“The people who are crazy enough to think they can change the world are the ones who do.” — Steve Jobs",
  "“The pain you feel today will be the strength you feel tomorrow.” — Unknown",
  "“Don’t wait for inspiration. It comes while working.” — Henri Matisse",
  "“Amateurs sit and wait; professionals get to work.” — Stephen King",
  "“What we fear doing most is usually what we most need to do.” — Tim Ferriss",
  "“Success demands singleness of purpose.” — Vince Lombardi",
  "“Go the extra mile—there’s no one on it.” — Grant Cardone",
  "“Success is peace of mind.” — John Wooden",
  "“Work hard, be kind, and amazing things will happen.” — Conan O’Brien",
  "“Never confuse movement with action.” — Ernest Hemingway",
  "“Be the change you wish to see.” — Mahatma Gandhi",
  "“Opportunities don’t happen, you create them.” — Chris Grosser",
  "“You were born to win.” — Zig Ziglar",
  "“Make each day your masterpiece.” — John Wooden",
  "“Do the best you can until you know better.” — Maya Angelou",
  "“Great things never came from comfort zones.” — Neil Strauss",
  "“The successful warrior is the average man with laser-like focus.” — Bruce Lee",
  "“Success is not something you pursue. It is something you attract.” — Jim Rohn",
  "“Life is short. Do stuff that matters.” — Unknown",
  "“Inaction breeds doubt and fear. Action breeds confidence and courage.” — Dale Carnegie",
  "“Every accomplishment starts with the decision to try.” — John F. Kennedy",
  "“To succeed in life, you need two things: ignorance and confidence.” — Mark Twain",
  "“Don’t stop until you’re proud.” — Unknown",
  "“The most effective way to do it is to do it.” — Amelia Earhart",
  "“Life rewards action.” — Unknown",
  "“Nothing worth having comes easy.” — Theodore Roosevelt",
  "“A goal is a dream with a finish line.” — Duke Ellington",
  "“Choose the harder right instead of the easier wrong.” — Military maxim",
  "“If you can’t stop thinking about it, don’t stop working for it.” — Unknown",
  "“Turn your can’ts into cans.” — Unknown",
  "“Someday is not a day of the week.” — Denise Brennan-Nelson",
  "“Everything has beauty, but not everyone sees it.” — Confucius",
  "“Never underestimate the power of dreams.” — John C. Maxwell",
  "“Be stronger than your excuses.” — Unknown",
  "“Success is not about money; it’s about impact.” — Tony Robbins",
  "“Great things take time.” — Unknown",
  "“The best view comes after the hardest climb.” — Unknown",
  "“Create a life you can’t wait to wake up to.” — Josie Spinardi",
  "“If you want something new, you have to stop doing something old.” — Peter Drucker",
  "“You can’t build a reputation on what you are going to do.” — Henry Ford",
  "“Do not let what you cannot do interfere with what you can do.” — John Wooden",
  "“The biggest room in the world is the room for improvement.” — Helmut Schmidt",
  "“The secret to getting ahead is getting started.” — Mark Twain",
  "“Out of difficulties grow miracles.” — Jean de La Bruyère",
  "“Action is the foundational key to success.” — Pablo Picasso",
  "“Your attitude determines your altitude.” — Zig Ziglar",
  "“Keep going. Be all in.” — Bryan Hutchinson",
  "“Don’t quit. Suffer now and live the rest of your life as a champion.” — Muhammad Ali",
  "“Go confidently in the direction of your dreams.” — Henry David Thoreau",
  "“The world makes way for the man who knows where he is going.” — Ralph Waldo Emerson",
  "“What you do speaks so loudly that I cannot hear what you say.” — Ralph Waldo Emerson",
  "“Well done is better than well said.” — Benjamin Franklin",
  "“Act boldly and unseen forces will come to your aid.” — Dorothea Brande",
  "“Do what you can, with what you have, where you are.” — Theodore Roosevelt",
  "“Whether you think you can or you think you can’t, you’re right.” — Henry Ford",
  "“The only impossible journey is the one you never begin.” — Tony Robbins",
  "“Dream big and dare to fail.” — Norman Vaughan",
  "“What we think, we become.” — Buddha",
  "“Hard times create strong men.” — G. Michael Hopf",
  "“Strength grows in the moments when you think you can’t go on.” — Unknown",
  "“Your only limit is you.” — Unknown",
  "“Success is not in what you have, but who you are.” — Bo Bennett",
  "“Be faithful to the moment.” — Unknown",
  "“Success is focusing the full power of all you are on what you have a burning desire to achieve.” — Wilfred Peterson",
  "“Your purpose in life is to find your purpose.” — Buddha",
  "“Persistence guarantees results.” — Paramahansa Yogananda",
  "“Discipline is choosing what you want most over what you want now.” — Abraham Lincoln",
  "“You are the artist of your life.” — Unknown",
  "“Don’t downgrade your dream to match your reality.” — Unknown",
  "“Stop doubting yourself. Work hard and make it happen.” — Unknown",
  "“One day or day one — you decide.” — Unknown",
  "“Prove them wrong.” — Unknown",
  "“You didn’t come this far to only come this far.” — Unknown",
  "“Success is no accident.” — Pelé",
  "“A comfort zone is a beautiful place, but nothing grows there.” — Unknown",
  "“If it’s important to you, you’ll find a way.” — Unknown",
  "“Courage is the commitment to begin without guarantee of success.” — Johann Wolfgang von Goethe",
  "“You become successful the moment you move toward a worthy goal.” — Earl Nightingale",
  "“The best time to start is now.” — Unknown",
  "“The more you do, the more you can do.” — Lucille Ball",
  "“Success leaves clues.” — Tony Robbins",
  "“Push yourself. No one else is going to do it for you.” — Unknown",
  "“Success is not measured by what you accomplish, but by the opposition you have overcome.” — Orison Swett Marden",
  "“Life rewards those who take action.” — Jim Rohn",
  "“Wake up with determination; go to bed with satisfaction.” — Unknown",
  "“You owe it to yourself to become everything you’ve ever dreamed of being.” — Unknown",
  "“The only way to predict the future is to create it.” — Peter Drucker",
  "“Your energy introduces you before you speak.” — Unknown",
  "“Consistency is what transforms average into excellence.” — Unknown",
  "“Ask yourself if what you’re doing today is getting you closer to where you want to be tomorrow.” — Anonymous",
  "“All progress takes place outside the comfort zone.” — Michael John Bobak",
  "“Results happen over time, not overnight.” — Unknown",
  "“Focus on the step in front of you, not the whole staircase.” — Unknown",
  "“You are capable of more than you know.” — Glinda",
  "“The moment you give up is the moment you let someone else win.” — Kobe Bryant",
  "“Success is not for the chosen few but for the few who choose.” — Unknown",
  "“If you want it, work for it.” — Unknown",
  "“You can’t pour from an empty cup.” — Unknown",
  "“If you’re not willing to risk the unusual, you will have to settle for the ordinary.” — Jim Rohn",
  "“Success is inevitable if your determination is unstoppable.” — Unknown",
  "“Turn your goals into habits and your habits into success.” — Unknown",
  "“Every day is a chance to be better.” — Unknown"
];
